import type { MistyServerMethod } from "@misty/contracts";

// Exhaustive: a new SDK method must receive an explicit server capability review.
export const methodScopes = {
  "mail.accounts.list": ["mail.read"],
  "mail.folders.list": ["mail.read"],
  "mail.threads.list": ["mail.read"],
  "mail.threads.get": ["mail.read"],
  "mail.threads.action": ["mail.write"],
  "mail.drafts.create": ["mail.write"],
  "mail.drafts.update": ["mail.write"],
  "mail.drafts.send": ["mail.write"],
  "spaces.get": ["spaces.read"],
  "spaces.members.list": ["spaces.read"],
  "notes.list": ["notes.read"],
  "notes.get": ["notes.read"],
  "notes.create": ["notes.write"],
  "notes.update": ["notes.write"],
  "notes.archive": ["notes.write"],
  "notes.delete": ["notes.write"],
  "notes.backlinks": ["notes.read"],
  "notes.collaboration.ticket": ["notes.write"],
  "notes.assets.reserve": ["notes.write"],
  "notes.assets.finalize": ["notes.write"],
  "notes.assets.download": ["notes.read"],
  "drawings.list": ["drawings.read"],
  "drawings.get": ["drawings.read"],
  "drawings.create": ["drawings.write"],
  "drawings.update": ["drawings.write"],
  "drawings.delete": ["drawings.write"],
  "drawings.collaboration.ticket": ["drawings.write"],
  "drawings.assets.reserve": ["drawings.write"],
  "drawings.assets.finalize": ["drawings.write"],
  "drawings.assets.download": ["drawings.read"],
  "tasks.list": ["tasks.read"],
  "tasks.create": ["tasks.write"],
  "tasks.update": ["tasks.write"],
  "tasks.delete": ["tasks.write"],
  "tasks.activity.list": ["tasks.read"],
  "tasks.move": ["tasks.write"],
  "agenda.list": ["tasks.read"],
  "roadmaps.list": ["roadmaps.read"],
  "roadmaps.get": ["roadmaps.read"],
  "roadmaps.create": ["roadmaps.write"],
  "roadmaps.update": ["roadmaps.write"],
  "roadmaps.delete": ["roadmaps.write"],
  "roadmaps.nodeDefinitions.list": ["roadmaps.read"],
  "roadmaps.nodeDefinitions.create": ["roadmaps.write"],
  "roadmaps.nodeDefinitions.update": ["roadmaps.write"],
  "roadmaps.nodeDefinitions.delete": ["roadmaps.write"],
  "roadmaps.milestones.create": ["roadmaps.write"],
  "roadmaps.milestones.update": ["roadmaps.write"],
  "roadmaps.milestones.delete": ["roadmaps.write"],
  "roadmaps.goals.create": ["roadmaps.write"],
  "roadmaps.goals.update": ["roadmaps.write"],
  "roadmaps.goals.delete": ["roadmaps.write"],
  "roadmaps.goals.setTasks": ["roadmaps.write"],
  "roadmaps.nodes.create": ["roadmaps.write"],
  "roadmaps.nodes.update": ["roadmaps.write"],
  "roadmaps.nodes.delete": ["roadmaps.write"],
  "roadmaps.edges.create": ["roadmaps.write"],
  "roadmaps.edges.update": ["roadmaps.write"],
  "roadmaps.edges.delete": ["roadmaps.write"],
  "roadmaps.layout.update": ["roadmaps.write"],
  "calendar.events.list": ["calendar.read"],
  "calendar.events.create": ["calendar.write"],
  "calendar.events.update": ["calendar.write"],
  "calendar.events.delete": ["calendar.write"],
  "calendar.sources.list": ["calendar.read"],
  "calendar.sources.create": ["calendar.write"],
  "calendar.sources.delete": ["calendar.write"],
  "calendar.google.calendars": ["calendar.read", "connections.read"],
  "calendar.sync": ["calendar.write", "tasks.write"],
  "connections.list": ["connections.read"],
  "connections.remove": ["connections.write"],
  "connections.authorize": ["connections.write"],
  "integrations.list": ["connections.read"],
  "integrations.bind": ["connections.write"],
} satisfies Record<MistyServerMethod, readonly string[]>;

export function authorizeMethod(method: MistyServerMethod, scopes: readonly string[]): boolean {
  return methodScopes[method].every((scope) => scopes.includes(scope));
}
