#!/bin/sh
set -eu

journal_env_file="${MISTY_JOURNAL_SERVER_ENV_FILE:-}"
stripe_secret_file="${STRIPE_WEBHOOK_SECRET_FILE:-}"

if [ -n "$journal_env_file" ]; then
  if [ ! -s "$journal_env_file" ]; then
    echo "Journal collaboration server secrets are missing at $journal_env_file." >&2
    exit 1
  fi
  existing_ticket_private_key="${JOURNAL_COLLAB_TICKET_PRIVATE_KEY:-}"
  existing_control_secret="${JOURNAL_COLLAB_CONTROL_SECRET:-}"
  existing_projection_secret="${JOURNAL_COLLAB_PROJECTION_SECRET:-}"
  existing_room_salt="${JOURNAL_COLLAB_ROOM_SALT:-}"
  set -a
  # The file is generated by the repository's secret generator.
  # shellcheck disable=SC1090
  . "$journal_env_file"
  set +a
  JOURNAL_COLLAB_TICKET_PRIVATE_KEY="${existing_ticket_private_key:-${JOURNAL_COLLAB_TICKET_PRIVATE_KEY:-}}"
  JOURNAL_COLLAB_CONTROL_SECRET="${existing_control_secret:-${JOURNAL_COLLAB_CONTROL_SECRET:-}}"
  JOURNAL_COLLAB_PROJECTION_SECRET="${existing_projection_secret:-${JOURNAL_COLLAB_PROJECTION_SECRET:-}}"
  JOURNAL_COLLAB_ROOM_SALT="${existing_room_salt:-${JOURNAL_COLLAB_ROOM_SALT:-}}"
  export \
    JOURNAL_COLLAB_TICKET_PRIVATE_KEY \
    JOURNAL_COLLAB_CONTROL_SECRET \
    JOURNAL_COLLAB_PROJECTION_SECRET \
    JOURNAL_COLLAB_ROOM_SALT
fi

if [ -n "$stripe_secret_file" ]; then
  if [ ! -s "$stripe_secret_file" ]; then
    echo "Stripe webhook secret is missing at $stripe_secret_file." >&2
    exit 1
  fi
  STRIPE_WEBHOOK_SECRET="$(tr -d '\r\n' < "$stripe_secret_file")"
  export STRIPE_WEBHOOK_SECRET
fi

exec /usr/local/bin/misty-server
