// Generated by scripts/migration/sync-app-catalog.mjs from the reviewed Store catalog.
// Do not edit this snapshot by hand.
export const catalogDocument = {
  "schema_version": 1,
  "host_protocol_version": 2,
  "apps": [
    {
      "id": "chat",
      "app_id": "com.misty.social",
      "slug": "social",
      "name": "Social",
      "publisher": "Misty",
      "description": "Conversations with people and agents in a Space.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "messages.read",
        "messages.write",
        "connections.read",
        "connections.write",
        "ai.read",
        "ai.write",
        "navigation.write",
        "activity.write",
        "library.read",
        "library.write",
        "files.read",
        "agents.read",
        "agents.write",
        "roadmaps.read",
        "clipboard.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/chat/1.1.0/desktop.zip",
        "sha256": "591c49ca9f00f04877f4d06758f3b67900b897a751df1602a7cf86c02a6129bb",
        "signature": "glcPI3djyOOZt0K1uMMOmFFa2Oh/SFMH14eQQ81ZwnY3aM+6s+n2hewidu8orC4zcRLWQdU5fSZwKqBV2hyBCw==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 1476313,
        "additional_storage_bytes": 5230215
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "journal",
      "app_id": "com.misty.journal",
      "slug": "journal",
      "name": "Journal",
      "publisher": "Misty",
      "description": "Notes and drawings for ideas worth keeping.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "ai.read",
        "ai.use",
        "ai.write",
        "clipboard.read",
        "clipboard.write",
        "connections.read",
        "connections.write",
        "drawings.read",
        "drawings.write",
        "files.read",
        "files.write",
        "links.open",
        "navigation.write",
        "notes.read",
        "notes.write",
        "profile.read",
        "spaces.read",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/journal/1.1.0/desktop.zip",
        "sha256": "b6f1eba2a41fcc6c69fa3683afe3e68f3eeafb006c1df1c30643bb8017fe540b",
        "signature": "hP3QNaZy2EVkqurMZBrzAbS6VZElfhitnvhmllV+9At1a2uwOiMU8SqS8rGJc0todWF696xAJtAR1qoJImz6AA==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 15386467,
        "additional_storage_bytes": 25535465
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "planner",
      "app_id": "com.misty.planner",
      "slug": "planner",
      "name": "Planner",
      "publisher": "Misty",
      "description": "Tasks, agenda, and roadmaps for work in motion.",
      "version": "1.1.0",
      "permission_version": 4,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "tasks.read",
        "tasks.write",
        "calendar.read",
        "calendar.write",
        "connections.read",
        "connections.write",
        "roadmaps.read",
        "roadmaps.write",
        "ai.read",
        "ai.write",
        "storage.read",
        "storage.write",
        "navigation.write",
        "links.open",
        "ai.use"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/planner/1.1.0/desktop.zip",
        "sha256": "5e69ee1ce5df7788f0612f8a4351e7065b013e331e397929f302b45d20fe4efe",
        "signature": "5nxUhWQWYa3u65sqi6U4d/MyJDculp37ds3N6tSWGExsd338EYibamZ+AnefQgYBo74LHWPhEd/6Cv8at4aRBA==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 704247,
        "additional_storage_bytes": 2430145
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "library",
      "app_id": "com.misty.library",
      "slug": "library",
      "name": "Library",
      "publisher": "Misty",
      "description": "Curated resources shared with a Space.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "library.read",
        "library.write",
        "profile.read",
        "files.read",
        "files.write",
        "connections.read",
        "connections.write",
        "ai.read",
        "ai.write",
        "navigation.write",
        "activity.write",
        "clipboard.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/library/1.1.0/desktop.zip",
        "sha256": "1d87e9e4ebfbb9621518a20c08f8d7b143c373b9851554eea83db333b5246ea1",
        "signature": "LDLX9pYqJRvjAvmi+0kDLFqYJB0jnsG1xB3pi4rvB/SJWG9tytwvFesACfnHniJvwGxAtZhYIeykLZpEL0z/Bg==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 1485426,
        "additional_storage_bytes": 5273048
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "inbox",
      "app_id": "com.misty.inbox",
      "slug": "inbox",
      "name": "Inbox",
      "publisher": "Misty",
      "description": "Updates and conversations that need attention.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "activity.read",
        "activity.write",
        "ai.read",
        "ai.use",
        "ai.write",
        "connections.read",
        "connections.write",
        "files.read",
        "links.open",
        "mail.read",
        "mail.write",
        "messages.read",
        "navigation.write",
        "spaces.read",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/inbox/1.1.0/desktop.zip",
        "sha256": "a0e238d51e408427c4d2d9a4dc5c14991965bdcf39a82ffc8de630ea9a61cc4e",
        "signature": "PDJccV0gyua36S42WMgYJnhqCpFMwLYwTLJWjdO0zi28rKb/1qUiEZc6D4KriX1ZnQt/BZgB2m61ydABRQxsAw==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 245445,
        "additional_storage_bytes": 952443
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "agents",
      "app_id": "com.misty.agents",
      "slug": "agents",
      "name": "Agents",
      "publisher": "Misty",
      "description": "Create and manage AI collaborators.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "agents.read",
        "agents.write",
        "profile.read",
        "ai.read",
        "ai.write",
        "mcp.read",
        "mcp.write",
        "automations.read",
        "automations.write",
        "devices.read",
        "devices.write",
        "navigation.write",
        "activity.write",
        "browser.read",
        "browser.write",
        "search.read",
        "search.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/agents/1.1.0/desktop.zip",
        "sha256": "75ff7f9d63987bbbb954c1f09934f8960786a682a61468988e6cecf79e083f8a",
        "signature": "a+UZQ/1aKAWtmu7B8Ud01oSmhbrN/abKyxvTo2U5ni73OLoROGIB28QzVLBcr2cnq2AtFC5oTpKvRLzAREQuBg==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 415669,
        "additional_storage_bytes": 1450694
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "files",
      "app_id": "com.misty.files",
      "slug": "files",
      "name": "Files",
      "publisher": "Misty",
      "description": "Browse local and connected files, and manage file transfers.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "activity.write",
        "connections.read",
        "connections.write",
        "files.read",
        "files.write",
        "media-search.read",
        "media-search.write",
        "navigation.write",
        "profile.read",
        "search.read",
        "spaces.read",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/files/1.1.0/desktop.zip",
        "sha256": "3e8ac7aca7c5a0b001d44cc1422f2044bdd63b4b90c6805b138d2d8fd85fe0d3",
        "signature": "cX6imbQDvBRwZoI8h/GZD+BM5vkTgzuyJ+LnWdbDpzXPLQtj9rlKuqqMlcLDNg7gRsHVFW8hDC02M3lcQXGEBQ==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 1487472,
        "additional_storage_bytes": 5279959
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "browser",
      "app_id": "com.misty.browser",
      "slug": "browser",
      "name": "Browser",
      "publisher": "Misty",
      "description": "Research beside your work.",
      "version": "1.1.0",
      "permission_version": 2,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "browser.navigate",
        "browser.inspect",
        "browser.interact",
        "clipboard.write",
        "links.open",
        "navigation.write",
        "ai.use"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/browser/1.1.0/desktop.zip",
        "sha256": "2578ab5b6c856eee46d3cdfb07326f434de7d1d401188461a34b2e9033ba6d4f",
        "signature": "AWRNHaNivqkfHQ/YK2Xnq1zLDAWh47kEId9+wl2DaLqqmOsZocnHCv4g3t69xa3EgHmhRoTNFSrJhj1PA+zqBw==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 174022,
        "additional_storage_bytes": 722980
      },
      "mobile": {
        "runtime": "embedded"
      }
    },
    {
      "id": "code",
      "app_id": "com.misty.code",
      "slug": "code",
      "name": "Code",
      "publisher": "Misty",
      "description": "A focused development workspace.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "code.read",
        "code.write",
        "ai.use",
        "navigation.write",
        "files.read",
        "files.write",
        "code.execute"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/code/1.1.0/desktop.zip",
        "sha256": "9d2dadccfa54e88d4d087835ba0d323c8fee055728d36c50b33024cb4fdaf1ec",
        "signature": "epZAhXracJAgpG/LdkrA981VOILpuipQqghhOlkfJfTk6yty/y4StZuf2MiyyhfI1+Xpljxk415b4L0reEaEAQ==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 794393,
        "additional_storage_bytes": 2552615
      },
      "mobile": {
        "runtime": "unsupported"
      }
    },
    {
      "id": "terminal",
      "app_id": "com.misty.terminal",
      "slug": "terminal",
      "name": "Terminal",
      "publisher": "Misty",
      "description": "Command-line tools inside the workspace.",
      "version": "1.1.0",
      "permission_version": 2,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "terminal.execute",
        "clipboard.read",
        "clipboard.write",
        "links.open",
        "ai.use"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/terminal/1.1.0/desktop.zip",
        "sha256": "98bd7b22e8c4a7e4b11d116c04209dd5bdd5ebd4f1eb281857ca07ffabff9eea",
        "signature": "5P+0kdHcfl5F+zU2/G44CgvBd8defOq9tVNxOeIY/51cNvEaikg+LCNTY1xZvs7i+zYDR4IMfSTNJ9lyI8f6CQ==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 242021,
        "additional_storage_bytes": 875518
      },
      "mobile": {
        "runtime": "unsupported"
      }
    }
  ],
  "signing": {
    "key_id": "misty-development-2026-01",
    "public_key": "11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo="
  }
} as const;
