// Code generated by misty-apps/scripts/sync-server-official-apps.mjs; DO NOT EDIT.

package appcatalog

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"strings"
)

const HostProtocolVersion = 2

type Runtime string

const (
	RuntimeDownloaded  Runtime = "downloaded"
	RuntimeHosted      Runtime = "hosted"
	RuntimeEmbedded    Runtime = "embedded"
	RuntimeUnsupported Runtime = "unsupported"
)

type PlatformRuntime struct {
	Runtime                Runtime `json:"runtime"`
	Entry                  string  `json:"entry,omitempty"`
	SHA256                 string  `json:"sha256,omitempty"`
	StyleSHA256            string  `json:"style_sha256,omitempty"`
	Signature              string  `json:"signature,omitempty"`
	SignatureKeyID         string  `json:"signature_key_id,omitempty"`
	DownloadBytes          int64   `json:"download_bytes,omitempty"`
	AdditionalStorageBytes int64   `json:"additional_storage_bytes,omitempty"`
}

type App struct {
	ID                 string          `json:"id"`
	AppID              string          `json:"app_id,omitempty"`
	Slug               string          `json:"slug,omitempty"`
	Name               string          `json:"name"`
	Publisher          string          `json:"publisher"`
	Description        string          `json:"description"`
	Version            string          `json:"version"`
	PermissionVersion  int             `json:"permission_version"`
	MinimumHost        int             `json:"minimum_host_protocol"`
	MinimumHostVersion string          `json:"minimum_host_version,omitempty"`
	Official           bool            `json:"official"`
	AgeRating          string          `json:"age_rating"`
	Scopes             []string        `json:"scopes"`
	Desktop            PlatformRuntime `json:"desktop"`
	Mobile             PlatformRuntime `json:"mobile"`
}

type catalogDocument struct {
	Apps []App `json:"apps"`
}

const generatedCatalog = `{
  "schema_version": 1,
  "host_protocol_version": 2,
  "apps": [
    {
      "id": "chat",
      "app_id": "com.misty.social",
      "slug": "social",
      "name": "Social",
      "publisher": "Misty",
      "description": "Conversations with people and agents in a Space.",
      "version": "1.1.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "messages.read",
        "messages.write",
        "connections.read",
        "connections.write",
        "ai.read",
        "ai.write",
        "navigation.write",
        "activity.write",
        "library.read",
        "library.write",
        "files.read",
        "agents.read",
        "agents.write",
        "roadmaps.read",
        "clipboard.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/chat/1.1.0-beta.1/desktop.zip",
        "sha256": "b4d211949d4df4709e5145457c121e0a20b644d435afa0f209f431998c282fd0",
        "signature": "odwgBrUN23eyszsEs1dPNnO05JqBfyZp8pPR0ShkJShwS4F1GvewDPnXanWY7HbEd/NyzlmgvEf5Ea4pzhCdAA==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 1479872,
        "additional_storage_bytes": 5230471
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "journal",
      "app_id": "com.misty.journal",
      "slug": "journal",
      "name": "Journal",
      "publisher": "Misty",
      "description": "Notes and drawings for ideas worth keeping.",
      "version": "1.1.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "ai.read",
        "ai.use",
        "ai.write",
        "clipboard.read",
        "clipboard.write",
        "connections.read",
        "connections.write",
        "drawings.read",
        "drawings.write",
        "files.read",
        "files.write",
        "links.open",
        "navigation.write",
        "notes.read",
        "notes.write",
        "profile.read",
        "spaces.read",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/journal/1.1.0-beta.1/desktop.zip",
        "sha256": "4ea90acf17023673ac79f1b84e8456b1b95f763a43749a3ee359ce510f54d8f5",
        "signature": "AlJOoGr970Y5D1edA3UmvarVmvrEM3ES1Y0jyRatixXKx9mVq1CSdZAbxhn2/o8crB3zUQ7Z/TeX5FMa9lJRBQ==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 15322770,
        "additional_storage_bytes": 25535521
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "planner",
      "app_id": "com.misty.planner",
      "slug": "planner",
      "name": "Planner",
      "publisher": "Misty",
      "description": "Tasks, agenda, and roadmaps for work in motion.",
      "version": "1.1.0-beta.1",
      "permission_version": 4,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "tasks.read",
        "tasks.write",
        "calendar.read",
        "calendar.write",
        "connections.read",
        "connections.write",
        "roadmaps.read",
        "roadmaps.write",
        "ai.read",
        "ai.write",
        "storage.read",
        "storage.write",
        "navigation.write",
        "links.open",
        "ai.use"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/planner/1.1.0-beta.1/desktop.zip",
        "sha256": "9a79d6e484460b89e78530756f16321922ed5668a031c582d6e9e0500565a74f",
        "signature": "+flqQkT7iuQ03Y1HKsrBN4m7Nfm6M+pRzaGd0+1uGZXIGPS56JBzvSXUazKuJjhNroXW6fGPMORTtdPGtwduDA==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 709787,
        "additional_storage_bytes": 2430201
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "library",
      "app_id": "com.misty.library",
      "slug": "library",
      "name": "Library",
      "publisher": "Misty",
      "description": "Curated resources shared with a Space.",
      "version": "1.1.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "library.read",
        "library.write",
        "profile.read",
        "files.read",
        "files.write",
        "connections.read",
        "connections.write",
        "ai.read",
        "ai.write",
        "navigation.write",
        "activity.write",
        "clipboard.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/library/1.1.0-beta.1/desktop.zip",
        "sha256": "99f7aa4bc8bf4a3ee72c1a44a6ad0c073e0a29b57ebf08e151d4519bc6d75129",
        "signature": "fW8XvlZ+sbUK2L/EgRkPgWz4eano5wty3lOKwDrLvlrAnjgDDfZVdiTTpxFlon23uwX6L3Vxm4ourxGDjZPmCQ==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 1490314,
        "additional_storage_bytes": 5273280
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "inbox",
      "app_id": "com.misty.inbox",
      "slug": "inbox",
      "name": "Inbox",
      "publisher": "Misty",
      "description": "Updates and conversations that need attention.",
      "version": "1.1.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "activity.read",
        "activity.write",
        "ai.read",
        "ai.use",
        "ai.write",
        "connections.read",
        "connections.write",
        "files.read",
        "links.open",
        "mail.read",
        "mail.write",
        "messages.read",
        "navigation.write",
        "spaces.read",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/inbox/1.1.0-beta.1/desktop.zip",
        "sha256": "7c6fbf8abb3ce910c390e870d2385a83a0199eddcb0f1ff44957ece858b97ff6",
        "signature": "Qp85JB/+ZS+alEhyih3el4jbCe+Wt84v5h8zj8fKiH15eVWVJ+l6k2X3kVV0frp4X8uDGmQ1dAYUGST4oamiCg==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 246115,
        "additional_storage_bytes": 952499
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "agents",
      "app_id": "com.misty.agents",
      "slug": "agents",
      "name": "Agents",
      "publisher": "Misty",
      "description": "Create and manage AI collaborators.",
      "version": "1.1.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "agents.read",
        "agents.write",
        "profile.read",
        "ai.read",
        "ai.write",
        "mcp.read",
        "mcp.write",
        "automations.read",
        "automations.write",
        "devices.read",
        "devices.write",
        "navigation.write",
        "activity.write",
        "browser.read",
        "browser.write",
        "search.read",
        "search.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/agents/1.1.0-beta.1/desktop.zip",
        "sha256": "e076aa0535b725dbb1b777d56b41444e6df06f311bdbec2d17581537595212f4",
        "signature": "33RINLvjESqBWmbmR/ep4xbRHot7BoSSzjDmeGoRPSNMOimolEaG5pEHd8Kk7+hehZzCemYrHiClBmRcd2uCBA==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 416878,
        "additional_storage_bytes": 1450913
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "files",
      "app_id": "com.misty.files",
      "slug": "files",
      "name": "Files",
      "publisher": "Misty",
      "description": "Browse local and connected files, and manage file transfers.",
      "version": "1.1.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "activity.write",
        "connections.read",
        "connections.write",
        "files.read",
        "files.write",
        "media-search.read",
        "media-search.write",
        "navigation.write",
        "profile.read",
        "search.read",
        "spaces.read",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/files/1.1.0-beta.1/desktop.zip",
        "sha256": "5215821d04efe2e0df7ede97ff8b0cefb8f37cf9ed887daf7886c77ac53842ef",
        "signature": "O+ghDfYIH20G5An8LTk+1/gUQput8j72/OZHtdDINrkM/R16py1isFOLybLSHdtDHMoVa7VyNjef3KctX9DlDQ==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 1492448,
        "additional_storage_bytes": 5280015
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "browser",
      "app_id": "com.misty.browser",
      "slug": "browser",
      "name": "Browser",
      "publisher": "Misty",
      "description": "Research beside your work.",
      "version": "1.1.0-beta.1",
      "permission_version": 2,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "browser.navigate",
        "browser.inspect",
        "browser.interact",
        "clipboard.write",
        "links.open",
        "navigation.write",
        "ai.use"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/browser/1.1.0-beta.1/desktop.zip",
        "sha256": "469d6be01caff8d838a00e0036095be85bb513d5aabe8e7d4f915e718c694b60",
        "signature": "fg4P1ThC5KRsmQ9vXBmMVVAdHBwvambEmreSF8J9oH+5Dn4hZnxgmh3QUU0ErH12YqmmmVFXOPzKUnDQy1zEBw==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 174373,
        "additional_storage_bytes": 723036
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "code",
      "app_id": "com.misty.code",
      "slug": "code",
      "name": "Code",
      "publisher": "Misty",
      "description": "A focused development workspace.",
      "version": "1.1.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "code.read",
        "code.write",
        "ai.use",
        "navigation.write",
        "files.read",
        "files.write",
        "code.execute"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/code/1.1.0-beta.1/desktop.zip",
        "sha256": "0e2e419231f20ce223bf3f504fa7e1f3b094f07399cb577056d5867d5b7987d5",
        "signature": "8wYt2aJRpZl/7/qpSgj7l1DdKmSIKoqh5b0r6vaB88hm1Emz9+F1togUD76J+S862Elyz0S8RN6qs69r4B1YDA==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 803936,
        "additional_storage_bytes": 2552671
      },
      "mobile": {
        "runtime": "unsupported"
      },
      "minimum_host_version": "0.1.0-beta.1"
    },
    {
      "id": "terminal",
      "app_id": "com.misty.terminal",
      "slug": "terminal",
      "name": "Terminal",
      "publisher": "Misty",
      "description": "Command-line tools inside the workspace.",
      "version": "1.1.0-beta.1",
      "permission_version": 2,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "terminal.execute",
        "clipboard.read",
        "clipboard.write",
        "links.open",
        "ai.use"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/terminal/1.1.0-beta.1/desktop.zip",
        "sha256": "997ee50c96397a75415140efb3104654d643c6c8f3669db18e2cb73aee579649",
        "signature": "6lguhzxS8zIdo92TMUtZmMHo+gkcPhLcbBVMcR3V2qKFE0pRjYiiTD4NwoMNlwuc7Cxqu7oZpFzw+6EP626HCg==",
        "signature_key_id": "misty-official-2026-09",
        "download_bytes": 243103,
        "additional_storage_bytes": 875574
      },
      "mobile": {
        "runtime": "unsupported"
      },
      "minimum_host_version": "0.1.0-beta.1"
    }
  ],
  "signing": {
    "key_id": "misty-official-2026-09",
    "public_key": "On4McQn01VlxUIFfW9W4iPzh8lTMU8cwgjbq/+E5YNg="
  }
}`

var officialApps = mustCatalogApps()

func mustCatalogApps() []App {
	var document catalogDocument
	if err := json.Unmarshal([]byte(generatedCatalog), &document); err != nil {
		panic("invalid generated official app catalog: " + err.Error())
	}
	return document.Apps
}

func Digest() string {
	return fmt.Sprintf("%x", sha256.Sum256([]byte(strings.TrimSpace(generatedCatalog))))
}

func All() []App {
	result := make([]App, len(officialApps))
	copy(result, officialApps)
	for index := range result {
		result[index].Scopes = append([]string(nil), result[index].Scopes...)
	}
	return result
}

func Find(id string) (App, bool) {
	id = strings.TrimSpace(strings.ToLower(id))
	for _, candidate := range officialApps {
		if candidate.ID == id {
			candidate.Scopes = append([]string(nil), candidate.Scopes...)
			return candidate, true
		}
	}
	return App{}, false
}

func NormalizeIDs(ids []string) ([]App, bool) {
	seen := make(map[string]bool, len(ids))
	apps := make([]App, 0, len(ids))
	for _, id := range ids {
		item, ok := Find(id)
		if !ok || seen[item.ID] {
			return nil, false
		}
		seen[item.ID] = true
		apps = append(apps, item)
	}
	return apps, true
}

func Defaults() []App {
	items, ok := NormalizeIDs([]string{"inbox", "chat", "journal", "files", "agents"})
	if !ok {
		panic("default Misty Apps are missing from the catalog")
	}
	return items
}
