// Code generated by misty-apps/scripts/sync-server-official-apps.mjs; DO NOT EDIT.

package appcatalog

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"strings"
)

const HostProtocolVersion = 2

type Runtime string

const (
	RuntimeDownloaded  Runtime = "downloaded"
	RuntimeHosted      Runtime = "hosted"
	RuntimeEmbedded    Runtime = "embedded"
	RuntimeUnsupported Runtime = "unsupported"
)

type PlatformRuntime struct {
	Runtime                Runtime `json:"runtime"`
	Entry                  string  `json:"entry,omitempty"`
	SHA256                 string  `json:"sha256,omitempty"`
	StyleSHA256            string  `json:"style_sha256,omitempty"`
	Signature              string  `json:"signature,omitempty"`
	SignatureKeyID         string  `json:"signature_key_id,omitempty"`
	DownloadBytes          int64   `json:"download_bytes,omitempty"`
	AdditionalStorageBytes int64   `json:"additional_storage_bytes,omitempty"`
}

type App struct {
	ID                 string          `json:"id"`
	AppID              string          `json:"app_id,omitempty"`
	Slug               string          `json:"slug,omitempty"`
	Name               string          `json:"name"`
	Publisher          string          `json:"publisher"`
	Description        string          `json:"description"`
	About              string          `json:"about,omitempty"`
	RepositoryURL      string          `json:"repository_url,omitempty"`
	Version            string          `json:"version"`
	PermissionVersion  int             `json:"permission_version"`
	MinimumHost        int             `json:"minimum_host_protocol"`
	MinimumHostVersion string          `json:"minimum_host_version,omitempty"`
	Official           bool            `json:"official"`
	AgeRating          string          `json:"age_rating"`
	RequiresApps       []string        `json:"requires_apps,omitempty"`
	Scopes             []string        `json:"scopes"`
	Desktop            PlatformRuntime `json:"desktop"`
	Mobile             PlatformRuntime `json:"mobile"`
}

type catalogDocument struct {
	Apps []App `json:"apps"`
}

const generatedCatalog = `{
  "schema_version": 1,
  "host_protocol_version": 2,
  "apps": [
    {
      "id": "chat",
      "app_id": "com.misty.social",
      "slug": "social",
      "name": "Social",
      "publisher": "Misty",
      "description": "Conversations with people and agents in a Space.",
      "version": "1.2.0-beta.1",
      "permission_version": 5,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "messages.read",
        "messages.write",
        "connections.read",
        "connections.write",
        "ai.read",
        "ai.write",
        "navigation.write",
        "activity.write",
        "library.read",
        "library.write",
        "files.read",
        "agents.read",
        "agents.write",
        "roadmaps.read",
        "clipboard.write",
        "browser.navigate",
        "browser.inspect",
        "browser.interact",
        "storage.read",
        "storage.write",
        "links.open"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/chat/1.2.0-beta.1/desktop.zip",
        "sha256": "8c9a83077accade71c7afb3f497e6f557f362475856f0818866d6831bd570c09",
        "signature": "gN3mmnGbl++xNO3oWb3gJWYlk+/W0Ed2SJOS0L2wbJuTGGBX5FryZsaAxjWmq47ADc0WRYtHLRzK9Q3Et/ALAQ==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 1673678,
        "additional_storage_bytes": 5548919
      },
      "mobile": {
        "runtime": "embedded"
      },
      "about": "Keep conversations with people and agents together in your Space. Connect supported social apps and keep their websites alongside your work.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/chat"
    },
    {
      "id": "journal",
      "app_id": "com.misty.journal",
      "slug": "journal",
      "name": "Journal",
      "publisher": "Misty",
      "description": "Notes and drawings for ideas worth keeping.",
      "version": "1.1.0-beta.2",
      "permission_version": 6,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "ai.read",
        "ai.use",
        "ai.write",
        "clipboard.read",
        "clipboard.write",
        "connections.read",
        "connections.write",
        "drawings.read",
        "drawings.write",
        "files.read",
        "files.write",
        "links.open",
        "navigation.write",
        "notes.read",
        "notes.write",
        "profile.read",
        "spaces.read",
        "storage.read",
        "storage.write",
        "network.fetch",
        "browser.navigate",
        "browser.inspect",
        "browser.interact"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/journal/1.1.0-beta.2/desktop.zip",
        "sha256": "8a3c2d944de6d522993dff43596b00695d8223b1f3008a9cd04fcf9a163aa577",
        "signature": "L9T1lkccsWRfpuljkrkU/eocZSdNMgvxritORSkkqAZXJnFmRrgB45YeFWKlurH0w9Qt58SEtYG82V8lFN60Dg==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 2612321,
        "additional_storage_bytes": 8722930
      },
      "mobile": {
        "runtime": "embedded"
      },
      "minimum_host_version": "0.1.0-beta.1",
      "about": "Write notes, collect ideas, and create drawings in your Space. Keep your thinking close to the conversations and projects it belongs to.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/journal"
    },
    {
      "id": "planner",
      "app_id": "com.misty.planner",
      "slug": "planner",
      "name": "Planner",
      "publisher": "Misty",
      "description": "Tasks, agenda, and roadmaps for work in motion.",
      "version": "1.1.0",
      "permission_version": 6,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "tasks.read",
        "tasks.write",
        "calendar.read",
        "calendar.write",
        "connections.read",
        "connections.write",
        "roadmaps.read",
        "roadmaps.write",
        "ai.read",
        "ai.write",
        "storage.read",
        "storage.write",
        "navigation.write",
        "links.open",
        "ai.use",
        "browser.navigate",
        "browser.inspect",
        "browser.interact"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/planner/1.1.0/desktop.zip",
        "sha256": "5e69ee1ce5df7788f0612f8a4351e7065b013e331e397929f302b45d20fe4efe",
        "signature": "5nxUhWQWYa3u65sqi6U4d/MyJDculp37ds3N6tSWGExsd338EYibamZ+AnefQgYBo74LHWPhEd/6Cv8at4aRBA==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 704247,
        "additional_storage_bytes": 2430145
      },
      "mobile": {
        "runtime": "embedded"
      },
      "about": "Organize tasks, plan your agenda, and track roadmaps in your Space. Connect supported planning apps alongside your work.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/planner"
    },
    {
      "id": "library",
      "app_id": "com.misty.library",
      "slug": "library",
      "name": "Library",
      "publisher": "Misty",
      "description": "Curated resources shared with a Space.",
      "version": "1.1.0",
      "permission_version": 4,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "library.read",
        "library.write",
        "profile.read",
        "files.read",
        "files.write",
        "connections.read",
        "connections.write",
        "ai.read",
        "ai.write",
        "navigation.write",
        "activity.write",
        "clipboard.write",
        "links.open",
        "browser.navigate",
        "browser.inspect",
        "browser.interact",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/library/1.1.0/desktop.zip",
        "sha256": "1d87e9e4ebfbb9621518a20c08f8d7b143c373b9851554eea83db333b5246ea1",
        "signature": "LDLX9pYqJRvjAvmi+0kDLFqYJB0jnsG1xB3pi4rvB/SJWG9tytwvFesACfnHniJvwGxAtZhYIeykLZpEL0z/Bg==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 1485426,
        "additional_storage_bytes": 5273048
      },
      "mobile": {
        "runtime": "embedded"
      },
      "about": "Keep shared files and resources organized in your Space. Browse collections and find the material your team needs.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/library"
    },
    {
      "id": "inbox",
      "app_id": "com.misty.inbox",
      "slug": "inbox",
      "name": "Inbox",
      "publisher": "Misty",
      "description": "Updates and conversations that need attention.",
      "version": "1.2.0-beta.1",
      "permission_version": 5,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "activity.read",
        "activity.write",
        "ai.read",
        "ai.use",
        "ai.write",
        "connections.read",
        "connections.write",
        "files.read",
        "links.open",
        "mail.read",
        "mail.write",
        "messages.read",
        "navigation.write",
        "spaces.read",
        "storage.read",
        "storage.write",
        "browser.navigate",
        "browser.inspect",
        "browser.interact"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/inbox/1.2.0-beta.1/desktop.zip",
        "sha256": "0f085d79d2295497c19aede9e6dce8ae49e9ad336332ba6f3837fe4d8bfd9eec",
        "signature": "8EBkQ2/KP8pVuT2e0rz2OB5EIt2tMU8jxEwwQAv1Y1CMTETZfKPegCn9ls0nBI2WwFQPORuCgWNN/CxKIi/LDw==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 441242,
        "additional_storage_bytes": 1270600
      },
      "mobile": {
        "runtime": "embedded"
      },
      "about": "Bring your connected mail accounts into one workspace. Open provider websites and use supported mail connections to work with your messages.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/inbox"
    },
    {
      "id": "agents",
      "app_id": "com.misty.agents",
      "slug": "agents",
      "name": "Agents",
      "publisher": "Misty",
      "description": "Create and manage AI collaborators.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "agents.read",
        "agents.write",
        "profile.read",
        "ai.read",
        "ai.write",
        "mcp.read",
        "mcp.write",
        "automations.read",
        "automations.write",
        "devices.read",
        "devices.write",
        "navigation.write",
        "activity.write",
        "browser.read",
        "browser.write",
        "search.read",
        "search.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/agents/1.1.0/desktop.zip",
        "sha256": "75ff7f9d63987bbbb954c1f09934f8960786a682a61468988e6cecf79e083f8a",
        "signature": "a+UZQ/1aKAWtmu7B8Ud01oSmhbrN/abKyxvTo2U5ni73OLoROGIB28QzVLBcr2cnq2AtFC5oTpKvRLzAREQuBg==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 415669,
        "additional_storage_bytes": 1450694
      },
      "mobile": {
        "runtime": "embedded"
      },
      "about": "Create and manage AI collaborators for your work. Configure their tools, conversations, and automations from one place.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/agents"
    },
    {
      "id": "files",
      "app_id": "com.misty.files",
      "slug": "files",
      "name": "Files",
      "publisher": "Misty",
      "description": "Browse local and connected files, and manage file transfers.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "activity.write",
        "connections.read",
        "connections.write",
        "files.read",
        "files.write",
        "media-search.read",
        "media-search.write",
        "navigation.write",
        "profile.read",
        "search.read",
        "spaces.read",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/files/1.1.0/desktop.zip",
        "sha256": "3e8ac7aca7c5a0b001d44cc1422f2044bdd63b4b90c6805b138d2d8fd85fe0d3",
        "signature": "cX6imbQDvBRwZoI8h/GZD+BM5vkTgzuyJ+LnWdbDpzXPLQtj9rlKuqqMlcLDNg7gRsHVFW8hDC02M3lcQXGEBQ==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 1487472,
        "additional_storage_bytes": 5279959
      },
      "mobile": {
        "runtime": "embedded"
      },
      "about": "Browse local files and connected storage, organize folders, and manage transfers alongside your other work.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/files"
    },
    {
      "id": "browser",
      "app_id": "com.misty.browser",
      "slug": "browser",
      "name": "Browser",
      "publisher": "Misty",
      "description": "Research beside your work.",
      "version": "1.2.0-beta.1",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "spaces.read",
        "browser.navigate",
        "browser.inspect",
        "browser.interact",
        "clipboard.write",
        "links.open",
        "navigation.write",
        "ai.use",
        "storage.read",
        "storage.write"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/browser/1.2.0-beta.1/desktop.zip",
        "sha256": "382c97d0f129f8e45ef102ed2afdabe124194ab3f6edaa3b7bbe643d79ce530a",
        "signature": "/I/KZpu3vpvHZIlk/HgHRg7lWwOGn0jTrGnRY64TEiF311uKIFjOqeQqfR/S0IrmEFXcuHHbjFB1MWbHwQFGBg==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 174580,
        "additional_storage_bytes": 724895
      },
      "mobile": {
        "runtime": "embedded"
      },
      "about": "Browse websites alongside your work. Keep pages open in tabs and bring useful page context into conversations with Misty.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/browser"
    },
    {
      "id": "code",
      "app_id": "com.misty.code",
      "slug": "code",
      "name": "Code",
      "publisher": "Misty",
      "description": "A focused development workspace.",
      "version": "1.1.0",
      "permission_version": 3,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "code.read",
        "code.write",
        "ai.use",
        "navigation.write",
        "files.read",
        "files.write",
        "code.execute"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/code/1.1.0/desktop.zip",
        "sha256": "9d2dadccfa54e88d4d087835ba0d323c8fee055728d36c50b33024cb4fdaf1ec",
        "signature": "epZAhXracJAgpG/LdkrA981VOILpuipQqghhOlkfJfTk6yty/y4StZuf2MiyyhfI1+Xpljxk415b4L0reEaEAQ==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 794393,
        "additional_storage_bytes": 2552615
      },
      "mobile": {
        "runtime": "unsupported"
      },
      "about": "Work on projects in an integrated editor. Browse project files and use development tools without leaving your workspace.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/code"
    },
    {
      "id": "terminal",
      "app_id": "com.misty.terminal",
      "slug": "terminal",
      "name": "Terminal",
      "publisher": "Misty",
      "description": "Command-line tools inside the workspace.",
      "version": "1.1.0",
      "permission_version": 2,
      "minimum_host_protocol": 2,
      "official": true,
      "age_rating": "4+",
      "scopes": [
        "terminal.execute",
        "clipboard.read",
        "clipboard.write",
        "links.open",
        "ai.use"
      ],
      "desktop": {
        "runtime": "downloaded",
        "entry": "https://apps.mistysys.com/official-apps/terminal/1.1.0/desktop.zip",
        "sha256": "98bd7b22e8c4a7e4b11d116c04209dd5bdd5ebd4f1eb281857ca07ffabff9eea",
        "signature": "5P+0kdHcfl5F+zU2/G44CgvBd8defOq9tVNxOeIY/51cNvEaikg+LCNTY1xZvs7i+zYDR4IMfSTNJ9lyI8f6CQ==",
        "signature_key_id": "misty-development-2026-01",
        "download_bytes": 242021,
        "additional_storage_bytes": 875518
      },
      "mobile": {
        "runtime": "unsupported"
      },
      "about": "Run commands and work with command-line tools inside Misty. Keep terminal sessions alongside your files and projects.",
      "repository_url": "https://github.com/misty-org/misty-apps/tree/main/apps/terminal"
    }
  ],
  "signing": {
    "key_id": "misty-development-2026-01",
    "public_key": "11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo="
  }
}`

var officialApps = mustCatalogApps()

func mustCatalogApps() []App {
	var document catalogDocument
	if err := json.Unmarshal([]byte(generatedCatalog), &document); err != nil {
		panic("invalid generated official app catalog: " + err.Error())
	}
	return document.Apps
}

func Digest() string {
	return fmt.Sprintf("%x", sha256.Sum256([]byte(strings.TrimSpace(generatedCatalog))))
}

func All() []App {
	result := make([]App, len(officialApps))
	copy(result, officialApps)
	for index := range result {
		result[index].RequiresApps = append([]string(nil), result[index].RequiresApps...)
		result[index].Scopes = append([]string(nil), result[index].Scopes...)
	}
	return result
}

func Find(id string) (App, bool) {
	id = strings.TrimSpace(strings.ToLower(id))
	for _, candidate := range officialApps {
		if candidate.ID == id {
			candidate.RequiresApps = append([]string(nil), candidate.RequiresApps...)
			candidate.Scopes = append([]string(nil), candidate.Scopes...)
			return candidate, true
		}
	}
	return App{}, false
}

func NormalizeIDs(ids []string) ([]App, bool) {
	seen := make(map[string]bool, len(ids))
	apps := make([]App, 0, len(ids))
	for _, id := range ids {
		item, ok := Find(id)
		if !ok || seen[item.ID] {
			return nil, false
		}
		seen[item.ID] = true
		apps = append(apps, item)
	}
	return apps, true
}

func Defaults() []App {
	items, ok := NormalizeIDs([]string{"inbox", "chat", "journal", "files", "agents"})
	if !ok {
		panic("default Misty Apps are missing from the catalog")
	}
	return items
}
